eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  #开发环境下使用 生产环境误开
  server:
    enable-self-preservation: false
  #instance:
    #hostname: clientName
spring:
  application:
    name: client